from pathlib import Path
import unittest


class ReadmeQualityTests(unittest.TestCase):
    def test_readme_is_readable_chinese_and_current_for_comic_v2(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertNotIn("锟", text)
        self.assertNotIn("�", text)
        self.assertNotIn("涓変", text)
        self.assertIn("三个臭皮匠", text)
        self.assertIn("AI 漫剧制片办公室", text)
        self.assertIn("确认故事后默认进入 V2 制片链", text)
        self.assertIn("启动检查", text)
        self.assertIn("模型页面", text)
        self.assertIn("测试按钮", text)
        self.assertIn("制片追溯", text)
        self.assertIn("故事版本", text)
        self.assertIn("资产版本", text)
        self.assertIn("视觉质检", text)
        self.assertIn("使用者填写自己的 Key", text)
        self.assertIn("python scripts/verify_first_run_readiness.py --format markdown", text)
        self.assertIn("python scripts/verify_comic_v2_delivery.py", text)
        self.assertIn("python scripts/verify_comic_v2_user_flow.py", text)
        self.assertIn("python scripts/verify_office_isolation.py --format markdown", text)
        self.assertIn("tests/fixtures/comic_v2_sample.json", text)
        self.assertIn("tests/fixtures/research_sample.json", text)
        self.assertIn("研究办公室演示提供阶段调研报告", text)
        self.assertIn("来源、数据、截图计划清单", text)
        self.assertIn("办公室协议", text)
        self.assertIn("/api/offices/protocols", text)
        self.assertIn("/api/workspaces/{workspace_id}/runtime-status", text)
        self.assertIn("产物完成度", text)
        self.assertIn("缺失产物", text)
        self.assertIn("creation_template", text)
        self.assertIn("recovery_actions", text)
        self.assertIn("no_key_demo", text)
        self.assertIn("model_preflight", text)
        self.assertIn("end_to_end_test", text)
        self.assertIn("/api/offices/{office_id}/launch-gates", text)
        self.assertIn("evidence_links", text)
        self.assertIn("样例交付物下载链接", text)
        self.assertIn("python scripts/doctor.py", text)
        self.assertIn("Office launch gates", text)
        self.assertIn("办公室上线门禁", text)
        self.assertIn("输入类型", text)
        self.assertIn("人工审核节点", text)
        self.assertIn("python -m unittest tests.test_sample_project_fixtures -q", text)
        self.assertIn("config.yaml", text)
        self.assertIn("不会提交到 GitHub", text)
        self.assertIn("docs/DEPLOYMENT_MODES.md", text)

    def test_deployment_modes_doc_separates_demo_local_and_saas(self):
        text = Path("docs/DEPLOYMENT_MODES.md").read_text(encoding="utf-8")

        self.assertNotIn("锟", text)
        self.assertNotIn("�", text)
        self.assertIn("演示模式", text)
        self.assertIn("本地真实模式", text)
        self.assertIn("未来 SaaS 模式", text)
        self.assertIn("不要把个人 API Key 写入前端", text)
        self.assertIn("Vercel", text)

    def test_deployment_modes_doc_gives_public_safety_decision_rules(self):
        text = Path("docs/DEPLOYMENT_MODES.md").read_text(encoding="utf-8")

        self.assertIn("## 快速选择", text)
        self.assertIn("公开作品集", text)
        self.assertIn("只开放 `/api/demo`", text)
        self.assertIn("禁用真实生产接口", text)
        self.assertIn("服务端代理", text)
        self.assertIn("访问者使用自己的 Key", text)
        self.assertIn("不要把 Key 放进前端 JavaScript、HTML、静态 JSON 或公开环境变量", text)
        self.assertIn("python scripts/check_no_secrets.py", text)
        self.assertIn("python scripts/verify_first_run_readiness.py --format markdown", text)
        self.assertIn("python scripts/verify_product_readiness.py --format markdown", text)
        self.assertIn("python scripts/verify_public_demo_mode.py --format markdown", text)
        self.assertIn("python scripts/verify_office_isolation.py --format markdown", text)
        self.assertIn("/api/demo/public-showcase", text)
        self.assertIn("公开演示模式验证", text)
        self.assertIn("公开展示清单", text)

    def test_readme_gives_new_user_model_setup_path(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("## 第一次使用应该怎么走", text)
        self.assertIn("先跑无 Key 演示", text)
        self.assertIn("再进入本地真实模式", text)
        self.assertIn("每个部门先点测试按钮", text)
        self.assertIn("最小可跑配置", text)
        self.assertIn("完整制片配置", text)
        self.assertIn("office_models 会覆盖全局 models", text)
        self.assertIn("没配置的部门会继续使用全局 models 里的同名部门", text)
        self.assertIn("视觉理解模型", text)
        self.assertIn("图片生成模型", text)


if __name__ == "__main__":
    unittest.main()
