from pathlib import Path
import unittest


class ReadmeQualityTests(unittest.TestCase):
    def test_readme_is_readable_chinese_and_current_for_comic_v2(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertNotIn("�", text)
        self.assertNotIn("锟", text)
        self.assertNotIn("閿", text)
        self.assertNotIn("娑撳", text)
        self.assertIn("# 三个臭皮匠", text)
        self.assertIn("actions/workflows/release-readiness.yml/badge.svg", text)
        self.assertIn("no-key-release-evidence", text)
        self.assertIn("本地优先的多 Agent 协作工作台", text)
        self.assertIn("AI 漫剧制片办公室", text)
        self.assertIn("确认故事后默认进入 V2 制片链", text)
        self.assertIn("中书省生成故事合同和视觉母版", text)
        self.assertIn("基础资产图", text)
        self.assertIn("视觉质检", text)
        self.assertIn("制片追溯", text)
        self.assertIn("故事版本", text)
        self.assertIn("资产版本", text)
        self.assertIn("使用者填写自己的 Key", text)
        self.assertIn("python scripts/doctor.py", text)
        self.assertIn("python scripts/verify_release_readiness.py --format markdown", text)
        self.assertIn("python scripts/verify_github_release_evidence.py --format markdown", text)
        self.assertIn("python scripts/verify_public_docs_readability.py --format markdown", text)
        self.assertIn("python scripts/verify_model_configuration_guidance.py --format markdown", text)
        self.assertIn("python scripts/verify_first_run_readiness.py --format markdown", text)
        self.assertIn("python scripts/verify_comic_v2_delivery.py --format markdown", text)
        self.assertIn("python scripts/verify_comic_v2_user_flow.py", text)
        self.assertIn("Common First-run Failures", text)
        self.assertIn("8080 端口占用", text)
        self.assertIn("tests.test_sample_project_fixtures", text)
        self.assertIn("研究办公室演示提供阶段调研报告", text)
        self.assertIn("来源、数据、截图计划清单", text)

    def test_readme_describes_office_protocols_and_launch_gates(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("## 办公室协议", text)
        self.assertIn("/api/offices/protocols", text)
        self.assertIn("/api/workspaces/{workspace_id}/runtime-status", text)
        self.assertIn("产物完成度", text)
        self.assertIn("缺失产物", text)
        self.assertIn("creation_template", text)
        self.assertIn("docs/NEW_OFFICE_STARTER_CHECKLIST.md", text)
        self.assertIn("required_demo_contract", text)
        self.assertIn("viewer_path", text)
        self.assertIn("interview_demo_script", text)
        self.assertIn("short_video_ads", text)
        self.assertIn("ecommerce_selection", text)
        self.assertIn("story_ip", text)
        self.assertIn("technical_project", text)
        self.assertIn("future_schema_validators", text)
        self.assertIn("future_recovery_events", text)
        self.assertIn("暂不开放原因", text)
        self.assertIn("recovery_actions", text)
        self.assertIn("no_key_demo", text)
        self.assertIn("model_preflight", text)
        self.assertIn("end_to_end_test", text)
        self.assertIn("/api/offices/{office_id}/launch-gates", text)
        self.assertIn("/api/offices/comic_production/real-production-readiness", text)
        self.assertIn("ready_for_real_run", text)
        self.assertIn("limited_planning_only", text)
        self.assertIn("Office launch gates", text)
        self.assertIn("输入类型", text)
        self.assertIn("人工审核节点", text)

    def test_readme_gives_new_user_model_setup_path(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("## 第一次使用应该怎么走", text)
        self.assertIn("先跑无 Key 演示", text)
        self.assertIn("再进入本地真实模式", text)
        self.assertIn("每个部门先点测试按钮", text)
        self.assertIn("模型台阶可以这样理解", text)
        self.assertIn("最小可跑配置", text)
        self.assertIn("完整制片配置", text)
        self.assertIn("工部生图模型 + 刑部视觉理解模型", text)
        self.assertIn("真实项目跑完后，再做三步验收", text)
        self.assertIn("python scripts/audit_comic_v2_handoffs.py --format markdown", text)
        self.assertIn(
            "python scripts/verify_comic_real_production_claim.py --manifest output/your_project/xxx_handoff_manifest.json --format markdown",
            text,
        )
        self.assertIn(
            "python scripts/verify_comic_v2_production_benchmark.py --manifest output/your_project/xxx_handoff_manifest.json --format markdown",
            text,
        )
        self.assertIn("can_claim_real_quality=True", text)
        self.assertIn("production_quality_verified", text)
        self.assertIn("否则只能说它完成了结构、流程或部分模型验证", text)
        self.assertIn("### 样例交付物怎么看", text)
        self.assertIn("AI 漫剧 Word 制片画布", text)
        self.assertIn("handoff_manifest.json", text)
        self.assertIn("AI 漫剧真实生产声明报告", text)
        self.assertIn("下游生产 quick-start", text)
        self.assertIn("Deliverable reading guide", text)
        self.assertIn("office_models", text)
        self.assertIn("会覆盖全局 `models`", text)
        self.assertIn("没配置的部门会继续使用全局 `models`", text)
        self.assertIn("视觉理解模型", text)
        self.assertIn("图片生成模型", text)
        self.assertIn("docs/MODEL_CONFIGURATION.md", text)

    def test_readme_model_table_matches_comic_production_roles(self):
        text = Path("README.md").read_text(encoding="utf-8")
        example = Path("config.example.yaml").read_text(encoding="utf-8")

        self.assertIn("| 兵部 | 文本镜头 / 视频提示词 |", text)
        self.assertIn("| 工部 | 生图模型，也就是图片生成模型 |", text)
        self.assertIn("Word 制片画布由已确认文本、提示词包和本地组装链路生成", text)
        self.assertIn("    bingbu:\n      provider: deepseek\n      model: deepseek-chat", text)
        self.assertIn("    gongbu:\n      provider: doubao\n      model: doubao-seedream-5", text)
        self.assertNotIn("| 兵部 | 生图模型 |", text)
        self.assertIn("    bingbu:\n      provider: deepseek\n      model: deepseek-chat", example)
        self.assertIn("    gongbu:\n      provider: doubao\n      model: doubao-seedream-5", example)
        self.assertIn("    xingbu:\n      provider: dashscope\n      model: qwen-vl-max", example)

    def test_readme_splits_public_experience_by_audience(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("## 三类读者怎么体验", text)
        self.assertIn("面试官", text)
        self.assertIn("开发者", text)
        self.assertIn("普通用户", text)
        self.assertIn("不需要 API Key", text)
        self.assertIn("样例交付物", text)
        self.assertIn("不要在公开页面、个人网站或 Vercel 展示页上传自己的 API Key", text)

    def test_readme_documents_public_demo_deployment_and_safety(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("docs/DEPLOYMENT_MODES.md", text)
        self.assertIn("docs/STATIC_SHOWCASE_DEPLOYMENT.md", text)
        self.assertIn("docs/PUBLIC_RELEASE_HANDOFF.md", text)
        self.assertIn("docs/PRODUCTIZATION_STATUS.md", text)
        self.assertIn("docs/REAL_PRODUCTION_CLAIMS.md", text)
        self.assertIn("python scripts/export_public_showcase.py", text)
        self.assertIn("python scripts/verify_static_public_showcase.py --format markdown", text)
        self.assertIn("python scripts/verify_static_public_showcase.py --format markdown --existing-dir dist/public-showcase", text)
        self.assertIn("dist/public-showcase/index.html", text)
        self.assertIn("data/comic_production_claim_report.json", text)
        self.assertIn("claim_upgrade_recovery", text)
        self.assertIn("downstream_handoff_decision", text)
        self.assertIn("structure_demo_only", text)
        self.assertIn("三条首次使用路径", text)
        self.assertIn("无 Key demo", text)
        self.assertIn("本地真实生产", text)
        self.assertIn("开发者扩展", text)
        self.assertIn("public_demo", text)
        self.assertIn("local_real_use", text)
        self.assertIn("developer_extension", text)
        self.assertIn("python scripts/verify_public_demo_mode.py --format markdown", text)
        self.assertIn("python scripts/verify_office_extension_governance.py --format markdown", text)
        self.assertIn("python scripts/export_office_creation_template.py --format markdown", text)
        self.assertIn("office_profile_skeleton", text)
        self.assertIn("public_demo_contract_skeleton", text)
        self.assertIn("最快验收路线", text)
        self.assertIn("七份下载物", text)
        self.assertIn("八个可复核文件", text)
        self.assertIn("核对 handoff manifest", text)
        self.assertIn("核对资产图片规格矩阵", text)
        self.assertIn("资产使用地图", text)
        self.assertIn("python scripts/check_no_secrets.py", text)
        self.assertIn("不要把自己的 API Key 暴露给访问者", text)
        self.assertIn("GitHub Actions", text)
        self.assertIn("Release readiness", text)
        self.assertIn("python scripts/verify_github_release_evidence.py --format markdown --contract-only", text)
        self.assertIn("不证明个人网站线上 Vercel 已经刷新", text)

    def test_readme_documents_development_checklist(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("python scripts/verify_development_checklist.py --format markdown", text)
        self.assertIn("python scripts/verify_development_checklist.py --format json --skip-release", text)
        self.assertIn("python scripts/verify_development_checklist.py --format markdown --run-tests --require-clean", text)
        self.assertIn("python -m unittest discover -s tests -q", text)

    def test_readme_documents_public_office_launch_matrix(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("办公室公开状态矩阵", text)
        self.assertIn("`AI 漫剧制片办公室`：当前主推办公室", text)
        self.assertIn("`研究办公室`：可公开展示固定样例", text)
        self.assertIn("`AI 漫剧办公室`：旧版兼容入口", text)
        self.assertIn("Office launch matrix: public_ready=2/3 / primary=1 / legacy=1", text)

    def test_readme_documents_image_evidence_recovery_path(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("image_production_evidence", text)
        self.assertIn("/api/tasks/{task_id}/comic-v2-trace.json", text)
        self.assertIn("/api/workspaces/{workspace_id}/comic/v2/quality/recover", text)
        self.assertIn("image_quality_summary", text)
        self.assertIn("downstream_handoff_decision", text)
        self.assertIn("handoff_allowed=false", text)
        self.assertIn("ready_for_downstream", text)
        self.assertIn("不能交给 Libtv", text)
        self.assertIn("rework_instructions", text)
        self.assertIn("claim_upgrade_recovery", text)
        self.assertIn("public_recovery_drill", text)
        self.assertIn("asset_usage_map", text)
        self.assertIn("身份基准图", text)
        self.assertIn("引用镜头", text)
        self.assertIn("保留故事/资产/提示词/旧 Word", text)
        self.assertIn("废片/返工", text)
        self.assertIn("regenerate_images", text)
        self.assertIn("fixture_only", text)
        self.assertIn("model_partial", text)

    def test_readme_documents_public_asset_requirement_matrix(self):
        text = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("Public Showcase Handoff Notes", text)
        self.assertIn("asset requirement matrix", text)
        self.assertIn("asset_usage_map", text)
        self.assertIn("three_view", text)
        self.assertIn("expression_sheet", text)
        self.assertIn("turnaround", text)
        self.assertIn("top_down", text)
        self.assertIn("clean_background_required=true", text)
        self.assertIn("/api/demo/comic-production", text)
        self.assertIn("/api/demo/public-showcase", text)
        self.assertIn("dist/public-showcase/showcase.json", text)
        self.assertIn("public/three-stooges/", text)
        self.assertIn("npm run check:showcase", text)
        self.assertIn("npm run check:online", text)
        self.assertIn("https://www.atticus.asia/three-stooges/", text)
        self.assertIn("Vercel authorization or redeploy", text)


if __name__ == "__main__":
    unittest.main()
